# Generated by Django 5.0.3 on 2024-06-05 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('last_location', models.CharField(max_length=100)),
                ('infected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('medication', models.IntegerField(default=0)),
                ('ammunition', models.IntegerField(default=0)),
                ('survivor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survivors.survivor')),
            ],
        ),
    ]
