# Generated by Django 5.0.3 on 2024-06-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0002_survivor_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='last_location',
            field=models.CharField(max_length=255),
        ),
    ]
