# Generated by Django 5.0.3 on 2024-06-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0003_alter_survivor_last_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survivor',
            name='unique_code',
        ),
        migrations.AlterField(
            model_name='survivor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
