# Generated by Django 5.0.3 on 2024-06-10 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0004_remove_survivor_unique_code_alter_survivor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='survivors.survivor')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survivors.survivor')),
            ],
        ),
    ]
